# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logRegApp', '0002_auto_20170325_0115'),
        ('coursesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_courses', to='coursesApp.AddCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_users', to='logRegApp.User')),
            ],
        ),
    ]
