# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logRegApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='flast_name',
            new_name='last_name',
        ),
    ]
